### ISSUE TITLE
Error when connecting with custom emails/ password. 

### ISSUE THREAD

**Issue by manudss** [patou/liste-envies#111]
When créating an application with custom email/password. Create a new account, and after connection, nothing works, their is server errors : 

java.lang.NullPointerException
	at fr.desaintsteban.liste.envies.service.AppUserService.lambda$getAppUserFromJwt$4(AppUserService.java:60)
	at fr.desaintsteban.liste.envies.service.AppUserService.getAppUser(AppUserService.java:80)
	at fr.desaintsteban.liste.envies.service.AppUserService.getAppUserFromJwt(AppUserService.java:58)
	at fr.desaintsteban.liste.envies.servlet.AuthFilter.doFilter(AuthFilter.java:51)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)

**Comment by manudss** [comment]
J'ai l'impression, que comme l'utilisateur n'est pas crée dans appUser, cela pose pb. Cela marchait bien avec des utilisateurs existants mais pas des nouveaux. @patou tu as une idée ?

**Comment by manudss** [comment]
Cela fonctionne avec un try catch : https://github.com/patou/liste-envies/pull/110/commits/bd8053caa77810a817b55ff72ce6f438ccfed778 

Mais je suis pas sûr si c'est la bonne chose ?

**Comment by patou** [comment]
Heu non là tu résoud rien.
Il faut regarder ta stackstrace, cela te met un null pointer exception sur ces lignes : 
```
            newAppUser.setName(user.get("name").asString());
            newAppUser.setPicture(user.get("picture").asString());
            newAppUser.setIsAdmin(false);
            newAppUser.setLoginProvider(user.get("iss").asString());
```

tu as le `user.get("name")` qui retourne null.

Il faut donc modifier ce code pour gérer qu'en fonction du provider, on a pas toujours les mêmes propriétés. (je pense que le picture ce sera aussi le cas.)
